all:
	gcc -g ./size.c -o size
	gcc -g ./maxMin.c -o maxMin_64
	gcc -g -m32 ./maxMin.c -o maxMin_32
	gcc -g ./struct.c -o struct
	gcc -g ./change.c -o change
	gcc -g ./str.c -o str

clean:
	rm size maxMin_64 maxMin_32 struct change str
